version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    networks:
      - elastic
    ports:
      - 9200:9200
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  kib01:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kib01
    networks:
      - elastic
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - es01

volumes: 
  data:
    driver: local

networks:
  elastic:
    driver: bridge
